import PDFDocument from 'pdfkit';
import { AppError } from '../utils/errors.js';
import { logger } from '../config/logger.js';

/**
 * Generates a TTE swap confirmation slip as a PDF buffer.
 * The slip contains the swap reference, train details, and each party's
 * before/after seat assignments — ready to show to the Train Ticket Examiner.
 *
 * @param {Object} session  - Fully confirmed swap session with parties
 * @returns {Promise<Buffer>}
 */
export const generateTteSlip = (session) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A6', margin: 28 });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', err => {
        logger.error('PDF generation error', { err });
        reject(new AppError('Failed to generate TTE slip', 500, 'PDF_ERROR'));
      });

      const W = doc.page.width - 56; // usable width

      // ── Header ──────────────────────────────────────────────────────────────
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .text('SeatSwap Confirmation Slip', { align: 'center' })
        .moveDown(0.3)
        .fontSize(8)
        .font('Helvetica')
        .fillColor('#666')
        .text('Please show this slip to your TTE for attendance marking', { align: 'center' })
        .fillColor('#000')
        .moveDown(0.6);

      // ── Divider ──────────────────────────────────────────────────────────────
      doc.moveTo(28, doc.y).lineTo(28 + W, doc.y).strokeColor('#ccc').lineWidth(0.5).stroke();
      doc.moveDown(0.5);

      // ── Swap reference ───────────────────────────────────────────────────────
      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor('#666')
        .text('Swap reference')
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#000')
        .text(`SW-${session.id.slice(-8).toUpperCase()}`)
        .moveDown(0.4);

      // ── Train info ───────────────────────────────────────────────────────────
      const firstParty = session.swap_session_parties?.[0];
      if (firstParty?.swap_request) {
        const req = firstParty.swap_request;
        doc
          .fontSize(8)
          .font('Helvetica')
          .fillColor('#666')
          .text('Train')
          .fontSize(10)
          .font('Helvetica-Bold')
          .fillColor('#000')
          .text(`${req.train_number} · ${req.train_name}`)
          .fontSize(9)
          .font('Helvetica')
          .text(`${req.journey_date} · ${req.travel_class}`)
          .moveDown(0.5);
      }

      doc.moveTo(28, doc.y).lineTo(28 + W, doc.y).strokeColor('#ccc').lineWidth(0.5).stroke();
      doc.moveDown(0.4);

      // ── Party-by-party seat moves ─────────────────────────────────────────────
      doc
        .fontSize(8)
        .font('Helvetica-Bold')
        .text('Seat reassignments')
        .moveDown(0.3);

      (session.swap_session_parties ?? []).forEach((party, i) => {
        const req = party.swap_request;
        if (!req) return;

        const fromLabel = `${req.current_coaches.join('/')}·${req.current_berths.join(',')}`;
        const toLabel = `${party.assigned_coaches?.join('/') ?? '?'}·${party.assigned_berths?.join(',') ?? '?'}`;

        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .text(`Party ${i + 1}`)
          .fontSize(8)
          .font('Helvetica')
          .text(`PNR: ${req.masked_pnr}`)
          .text(`Was: ${fromLabel}    →    Now: ${toLabel}`)
          .moveDown(0.3);
      });

      doc.moveTo(28, doc.y).lineTo(28 + W, doc.y).strokeColor('#ccc').lineWidth(0.5).stroke();
      doc.moveDown(0.4);

      // ── Footer ────────────────────────────────────────────────────────────────
      doc
        .fontSize(7)
        .fillColor('#888')
        .text(
          `Confirmed at ${new Date(session.completed_at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST`,
          { align: 'center' }
        )
        .text('This slip is digitally generated by SeatSwap. All parties have mutually confirmed.', {
          align: 'center',
        });

      doc.end();
    } catch (err) {
      reject(new AppError('Failed to generate TTE slip', 500, 'PDF_ERROR'));
    }
  });
};
